- type: job
  id: ESChemist
  name: ESjob-name-chemist
  description: ESjob-description-chemist
  playTimeTracker: ESJobChemist
  startingGear: ESChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-hop
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ESChemistGear
  equipment:
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesColorBlue
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    jumpsuit: ClothingUniformJumpsuitChemistry
    outerClothing: ClothingOuterCoatLabChemOpened
    back: ClothingBackpackChemistry
    pocket1: HandLabeler